collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    fields:
      - { name: "language", label: "Language", widget: "select", options: ["en", "km"] }
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "body", label: "Body", widget: "markdown" }
