# public/admin/config.yml
backend:
  name: github
  repo: micky-code/your-repo-name # replace with your GitHub username and repository name
  branch: main # or the branch you want to use for CMS content
  auth_scope: "repo" # permissions needed for Decap CMS to push changes

media_folder: "public/uploads" # Where uploaded files will be stored
public_folder: "/uploads"

# Authentication using GitHub OAuth
site_url: "https://yoursite.com" # Your site's URL
auth_endpoint: "https://api.netlify.com" # Use Netlify's identity widget for OAuth authentication

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/content/pages/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Hero Image", name: "hero_image", widget: "image" }
