backend:
  name: github
  repo: micky-code/project-testing # Your GitHub repository
  branch: main # Branch to update

media_folder: "public/images" # Folder to store uploaded files
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/posts" # Folder for your posts
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }

  - name: "homepage"
    label: "Homepage Content"
    folder: "src/content" # Folder for homepage content
    create: true
    slug: "index" # Fixed slug for the homepage
    fields:
      - { name: "title", label: "Homepage Title", widget: "string" }
      - { name: "intro", label: "Introduction", widget: "text" }
      - { name: "content", label: "Homepage Content", widget: "markdown" }
      - { name: "footer", label: "Footer Content", widget: "markdown" }